{
 "title": "Tasklist",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(zeebe_stream_processor_events_total, namespace)"
   },
   {
    "name": "partition",
    "query": "label_values(zeebe_exporter_events_total{namespace=~\"$namespace\"}, partition)"
   }
  ]
 },
 "panels": [
  {
   "title": "Exported and processed Zeebe records rate per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tasklist_events_processed_total{namespace=~\"$namespace\",partition=~\"$partition\"}[10m])) by (status)",
     "legendFormat": "processed by tasklist: partition {{$partition}} - {{status}}"
    },
    {
     "expr": "sum(rate(zeebe_exporter_events_total{namespace=~\"$namespace\",valueType=~\"JOB|PROCESS_INSTANCE|VARIABLE|VARIABLE_DOCUMENT|DEPLOYMENT\",action=~\"exported\",partition=~\"$partition\"}[10m]))",
     "legendFormat": "exported by Zeebe: partition {{$partition}}"
    }
   ]
  },
  {
   "title": "Import latencies, 10 min average, sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(tasklist_import_query_seconds_sum[10m])/rate(tasklist_import_query_seconds_count[10m])>0)",
     "legendFormat": "Importer read latency"
    },
    {
     "expr": "avg(rate(tasklist_import_index_query_seconds_sum[10m])/rate(tasklist_import_index_query_seconds_count[10m])>0)",
     "legendFormat": "Importer index latency"
    }
   ]
  },
  {
   "title": "Finished instances archiving rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tasklist_archived_process_instances_total{namespace=\"$namespace\"}[10m]))",
     "legendFormat": "{{pod}}: archived"
    },
    {
     "expr": "sum(rate(tasklist_events_processed_finished_process_instances_total{namespace=\"$namespace\"}[10m]))",
     "legendFormat": "{{pod}}: finished"
    }
   ]
  },
  {
   "title": "Archiver latencies, 10 min average, sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(tasklist_archiver_query_seconds_sum[10m])/rate(tasklist_archiver_query_seconds_count[10m]))",
     "legendFormat": "Archiver read latency"
    },
    {
     "expr": "avg(rate(tasklist_archiver_reindex_query_seconds_sum[10m])/rate(tasklist_archiver_reindex_query_seconds_count[10m]))",
     "legendFormat": "Archiver reindex latency"
    },
    {
     "expr": "avg(rate(tasklist_archiver_delete_query_seconds_sum[10m])/rate(tasklist_archiver_delete_query_seconds_count[10m]))",
     "legendFormat": "Archiver delete latency"
    }
   ]
  },
  {
   "title": "Processed event rate per event type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tasklist_events_processed_total{namespace=~\"$namespace\",status=\"succeeded\",partition=~\"$partition\"}[10m])) by (type)",
     "legendFormat": "{{type}} {{$partition}}: Tasklist"
    },
    {
     "expr": "sum(rate(zeebe_exporter_events_total{namespace=\"$namespace\",valueType=~\"JOB|PROCESS_INSTANCE|VARIABLE|DEPLOYMENT\",action=\"exported\",partition=~\"$partition\"}[10m])) by (valueType)",
     "legendFormat": "{{valueType}} {{$partition}}: Zeebe"
    }
   ]
  }
 ]
}